### ISSUE TITLE
Minecraft 1.17 crash

### ISSUE THREAD

**Issue by K0smic** [cominixo/BiomePicker#2]
[crash-2021-06-17_17.56.23-client.txt](https://github.com/cominixo/BiomePicker/files/6671590/crash-2021-06-17_17.56.23-client.txt)

The game crash after i select Giant Tree Taiga.

**Comment by Majarou** [comment]
The issue stems from a missing string or such. It happens anytime someone tries to open the menu to choose a biome

**Comment by cominixo** [comment]
Sorry for the wait, should be fixed in 1.1.1
